function [dlg_title, sub_title_field, prompt, defAns] = brant_preprocess_parameters(userdata, preps_all)


dlg_title = userdata;

switch(userdata)
    case 'slicetiming'
        
        sub_title_field = {...
            'Slice Timing';...
            ''};
        
        prompt{1} = {...
            'slice order:',                         'numeric',     'slice_order';...
            'tr(s):',                               'numeric',     'tr';...
            'reference slice',                      'numeric',     'refslice';...
            'prefix:',                              'string',      'prefix'};
    case 'realign'
        
        sub_title_field = {...
            'Estimate', 'Write';...
            'eoptions', 'roptions'};
        
        prompt{1} = {...
            'quality'	,         'numeric'		,	'quality'	;...
            'sep'		,         'numeric'		,	'sep'    	;...
            'fwhm'		,         'numeric'		,	'fwhm'   	;...
            'rtm'		,         'numeric'		,	'rtm'    	;...
            'wrap'		,         'numeric'		,	'wrap'   	;...
            ...'weight'	,         'file_txt'	,	'weight' 	;...
            'interp'	,         'numeric'		,	'interp' 	};
        
        
        prompt{2} = {...
            'which' 	,	'numeric'	,	'which' 	;...
            'interp'	,	'numeric'	,	'interp'	;...
            'wrap'  	,	'numeric'	,	'wrap'  	;...
            'mask'  	,	'numeric'	,	'mask'  	;...
            'prefix'	,	'string'	,	'prefix'	};
        
    case 'coregister'
%         sub_title_field = {...
%             'Subject Info', 'Estimate', 'Write';...
%             'subj', 'eoptions', 'roptions'};
        sub_title_field = {...
            'Subject Info', 'Estimate';...
            'subj', 'eoptions'};
        
        prompt{1} = {...
            'reference'           ,	'string'		,	'filetype_ref'  	;...
            'source'		,	'string'		,	'filetype_src'  	;...
            'seg&bet'       ,   'numeric',       'seg_bet_ind'};
        ...'other'         ,   'string'        ,   'filetype_other'
            
    
    prompt{2} = {...
        'object fun'		,	'popup'        ,	'cost_fun'	;...
        'sep'		,	'numeric'		,	'sep'  	;...
        'tol'		,	'numeric'		,	'tol'  	;...
        'fwhm'		,	'numeric'			,	'fwhm'};
    
    
%     prompt{3} = {...
%         'interp'	,	'numeric'        ,	'interp'	;...
%         'wrap'		,	'numeric'		,	'wrap'  	;...
%         'mask'		,	'numeric'		,	'mask'  	;...
%         'prefix'		,	'string'		,	'prefix'};
    
    case 'normalise'
        
        sub_title_field = {...
            'Subject Info', 'Estimate', 'Write';...
            'subj', 'eoptions', 'roptions'};
        
        prompt{1} = {...
            'source'		,	'string'		,	'filetype_src'  	;...
            'weight' 		,	'string'		,	'filetype_wt'};
        %             'source'		,	'file_txt'		,	'source'  	;...
        %             'wtsrc' 		,	'file_txt'		,	'wtsrc'  	;...
        %             'filetype'      ,   'string'        ,   'filetype'  };
        
        prompt{2} = {...
            'template'		,	'file_img_*'	,	'template'	;...
            'smosrc'		,	'numeric'		,	'smosrc'  	;...
            'smoref'		,	'numeric'		,	'smoref'  	;...
            'regtype'		,	'popup'			,	'regtype' 	;...
            'cutoff'		,	'numeric'		,	'cutoff'  	;...
            'nits'			,	'numeric'		,	'nits'    	;...
            'reg'			,	'numeric'		,	'reg'     	};
        
        prompt{3} = {...
            'preserve'	,	'numeric'	,	'preserve'	;...
            'bb'      	,	'numeric'	,	'bb'      	;...
            'vox'     	,	'numeric'	,	'vox'     	;...
            'interp'  	,	'numeric'	,	'interp'  	;...
            'wrap'    	,	'numeric'	,	'wrap'    	;...
            'prefix'  	,	'string'	,	'prefix'  	};

	case 'normalise12'
        
        sub_title_field = {...
            'Subject Info'  , 'Estimate'    , 'Write';...
            'subj'          , 'eoptions'    , 'woptions'};
        
        prompt{1} = {...
            'source'		,	'string'	,	'filetype_src'};
        
        prompt{2} = {...
            'biasreg'		,	'numeric'	,	'biasreg'	;...
            'biasfwhm'		,	'numeric'	,	'biasfwhm'  	;...
            'tpm'           ,	'file_img_*',	'tpm'  	;...
            'affreg'		,	'popup'		,	'affreg' 	;...
            'reg'           ,	'numeric'	,	'reg'  	;...
            'fwhm'			,	'numeric'	,	'fwhm'    	;...
            'samp'			,	'numeric'	,	'samp'     	};
        
        prompt{3} = {...
            'bb'      	,	'numeric'	,	'bb'      	;...
            'vox'     	,	'numeric'	,	'vox'     	;...
            'interp'  	,	'numeric'	,	'interp'  	;...
            'prefix'  	,	'string'	,	'prefix'  	;...
            };
        
%     case 'denoise_old' % version 1
%         prompt{1} = {...
%             'timepoints'	,	'numeric'	,	'timepoints'	;...
%             'voxelsize' 	,	'numeric'	,	'voxelsize' 	;...
%             'gzip output'   ,	'box'		,	'gzip'          	;...
%             'prefix'    	,	'string'	,	'prefix'    	}	;
%         prompt{2} = {...
%             'constant *'       ,	'box'       ,	'constant'    ;...
%             'linear drift'     ,	'box'       ,	'linear_drift'};
%         prompt{3} = {...
%             'whole brain'      ,   'box_file_img_*'    ,   'wholebrain'    ;...
%             'white matter'     ,   'box_file_img'  ,   'wm'            ;...
%             'gray matter'      ,   'box_file_img'  ,   'gm'            ;...
%             'csf'              ,   'box_file_img'  ,   'csf'           ;...
%             'global mean'      ,   'box'               ,   'glob'          };
%         prompt{4} = {...
%             'head motion'      ,	'box'       ,   'head';...
%             'motion''s deriv'  ,	'box'       ,   'deriv';...
%             'filetype'         ,   'string'    ,   'filetype'};
        
%     case 'denoise' % version 2
%         sub_title_field = {...
%             'Data Information', 'Trends & Tissue', 'Headmotion Model', 'Filter';...
%             'subj', 'detrend_mask', 'motion', 'filter'};
%         
%         prompt{1} = {...
%             'brain mask'    ,   'box_file_img', 'wb_mask'   ;...
%             'GSR'      ,	'radio'       ,   'gsr';...
%             'no GSR'      ,	'radio'       ,   'nogsr';...
%             'GSR and no GSR'      ,	'radio'       ,   'bothgsr';...
%             'multi-regression prefix'    	,	'string'	,	'prefix_denoise'    ;...
%             'filter prefix'     ,       'string'            ,   'prefix_filter';...
%             'reslice masks(?)'       ,	'box'       ,	'reslice_mask_ind'    ;...
%             };
%         prompt{2} = {...
%             'switch on/off',     'box_panel',      'tissue_trends_ind';...
%             'demean&detrend'       ,	'box'       ,	'detrend'    ;...
%             'global signal mask'      ,   'box_file_img'    ,   'gs'    ;...
%             'white matter mask'     ,   'box_file_img'  ,   'wm'            ;...
%             'CSF mask'              ,   'box_file_img'  ,   'csf'           ;...
%             'user defined mask'      ,   'box_file_img'  ,   'user_mask'            ;...
%             'tissue derivtives',           'box',          'tissue_deriv'};
%         prompt{3} = {...
%             'switch on/off',     'box_panel',      'hm_model_ind';...
%             'filetype (R)'         ,   'string'    ,   'filetype';...
%             '[R]'      ,	'radio'       ,   'params_6';...
%             '[R,R'']'      ,	'radio'       ,   'params_12';...
%             '<html>[R,R<sup>2</sup>,R<sub>t-1</sub>,R<sub>t-1</sub><sup>2</sup>]</html>',	'radio',   'params_24';...
%             'scrub&regress (FD)',     'box_numeric',      'scrub_FD';...
%             'apply temporal mask',           'box',          'use_temp_mask'};
%         prompt{4} = {...
%             'switch on/off',     'box_panel',      'filter_ind';...
%             'tr(s)'            ,       'numeric'           ,   'tr';...
%             'Lower cutoff(Hz)' ,       'numeric'           ,   'lower_cutoff';...
%             'Upper cutoff(Hz)' ,       'numeric'           ,   'upper_cutoff';...
%             };
        
    case 'denoise' % version 3
        sub_title_field = {...
            'Masks & Motion', 'Regression Model', 'Filter';... %Regression Model', 'Filter', 'Options
            'space_mask', 'reg_mdl', 'fil_opt'};
        
        prompt{1} = {...
            'Common Space(e.g. MNI)'      ,	'radio'       ,   'space_comm';...
            'brain mask'    ,   'box_file_img_struct', 'mask_wb'   ;...
            'global signal mask'      ,   'box_file_img_struct'    ,   'mask_gs'    ;...
            'white matter mask'     ,   'box_file_img_struct'  ,   'mask_wm'            ;...
            'CSF mask'              ,   'box_file_img_struct'  ,   'mask_csf'           ;...
            'Individual Space'      ,	'radio'       ,   'space_ind';...
            'WB filetype'         ,   'string_thr'    ,   'ft_wb';...
            'GS filetype'         ,   'string_thr'    ,   'ft_gs';...
            'WM filetype'         ,   'string_thr'    ,   'ft_wm';...
            'CSF filetype'         ,   'string_thr'    ,   'ft_csf';...
            'reslice masks with'		,	'popup'			,	'mask_res_type' 	;...
            'Motion filetype'         ,   'string'    ,   'ft_motion';...
            };
        prompt{2} = {...
            'linear trend'       ,	'box'       ,	'lin_trend'    ;...
            'quadratic trend'       ,	'box'       ,	'quad_trend'    ;...
            '',     'text',      'char_info';...
            '',     'multi_box',      'regressors';...
            '',     'text',      'spike_info';...
            ...'despike'      ,	'radio'       ,   'despike';...
            ...'spikereg'      ,	'radio'       ,   'spikereg';...
            'scrubbing'      ,	'box'       ,   'scrubbing';...
            'FD Threshold(mm)'            ,       'numeric'           ,   'fd_thr';...
            };
        prompt{3} = {...
            'tr(s)'            ,       'numeric'           ,   'tr';...
            'Lower cutoff(Hz)' ,       'numeric'           ,   'lower_cutoff';...
            'Upper cutoff(Hz)' ,       'numeric'           ,   'upper_cutoff';...
            '',     'text',      'opt';...
            'Regression + Filter'      ,	'radio'       ,   'reg_filter';...
            'Filter + Regression'      ,	'radio'       ,   'filter_reg';...
            'Regression only'      ,	'radio'       ,   'reg_only';...
            'Filter only'      ,	'radio'       ,   'filter_only';...
            'Run with and without GSR'      ,	'box'       ,   'gsr_nogsr';...
            'Save only last results'      ,	'box'       ,   'save_last';...
            'Output to *.gz format'      ,	'box'       ,   'gzip_output';...
            'multi-regression prefix'    	,	'string'	,	'prefix_reg'    ;...
            'filter prefix'     ,       'string'            ,   'prefix_filter';...
            };
        
    case 'filter'
        
        sub_title_field = {...
            'Filter', '';...
            '', ''};
        
        prompt{1} = {...
            'Lower cutoff(Hz)' ,       'numeric'           ,   'lower_cutoff';...
            'Upper cutoff(Hz)' ,       'numeric'           ,   'upper_cutoff'};
        
        prompt{2} = {...
            'tr(s)'            ,       'numeric'           ,   'tr';...
            'timepoints'       ,       'numeric'           ,   'timepoints';...
            'prefix'           ,       'string'            ,   'prefix';...
            'gzip output'      ,       'box'               ,	'gzip'};
    case 'smooth'
        
        sub_title_field = {...
            'Smooth',;...
            ''};
        
        prompt{1} = {...
            'fwhm'             ,       'numeric'   ,   'fwhm';...
            'prefix'           ,       'string'    ,   'prefix'};
end


for m = 1:size(sub_title_field, 2)
    if ~isempty(sub_title_field{2, m})
        for n = 1:size(prompt{m}, 1)
            defAns.(sub_title_field{2, m}).(prompt{m}{n, 3}) = preps_all.(userdata).(sub_title_field{2, m}).(prompt{m}{n, 3});
        end
    else
        for n = 1:size(prompt{m}, 1)
            defAns.(prompt{m}{n, 3}) = preps_all.(userdata).(prompt{m}{n, 3});
        end
    end
end
