function dlg_out = brant_inputdlg(dlg_title, dlg_rstbtn, coltitle, prompt, defAns, field_fun, subfield_fun, h_prep_main)

ncols = length(prompt);

if length(prompt) ~= length(defAns)
    tmpdlg = warndlg('Input Error! Length of prompt should equal to length of defAns');
    uiwait(tmpdlg);
    dlg_out = cell(ncols,1);
    return;
end

figColor = 0.9*[1 1 1];

% 用来统计每一列的长度
cols = zeros(ncols,1);

for n = 1:ncols
    cols(n) = size(prompt{n},1);
end

% 用来标记每个输入框的位置
posText = cell(ncols,1);
posChB = cell(ncols,1);
posRB = cell(ncols,1);
posBF = cell(ncols,1);

if ncols == 1
    comp = 1;
else
    comp = 0;
end

figsize.x = 40 + 100 * (ncols+comp) + (ncols-1+comp)*20 - comp*(1-dlg_rstbtn)*110 + (ncols == 1) * 60;  % width
figsize.y = 45*(max(cols) + 1) + 120;   % height
btn_bkgColor = [0.94 0.94 0.94];


h_main = findobj(0,  'Name',             'brant_Preprocessing',...
                     'Tag',              'brant_preprocess_main');
pos_main = get(h_main, 'Position');

hfig_inputdlg = figure(...
    'IntegerHandle',    'off',...
    'Position',         [pos_main(1) + pos_main(3) + 16, pos_main(2) + pos_main(4) - figsize.y, figsize.x, figsize.y],...
    'Color',            figColor,...
    'Name',             dlg_title,...
    'CloseRequestFcn',  @cancel_cb,...
    'UserData',         'fig_inputdlg',...
    'NumberTitle',      'off',...
    'Tag',              'figInput',...	
    'Units',            'pixels',...
    'Resize',           'off',...	
    'MenuBar',          'none',...    
    'Visible',          'on');

% movegui(hfig_inputdlg, 'center');
% labels and input boxes
for n = 1:ncols
    posText{n} = cell(size(prompt{n},1),1);
    posChB{n} = cell(size(prompt{n},1),1);
    posRB{n} = cell(size(prompt{n},1),1);
    posBF{n} = cell(size(prompt{n},1),1);
    if ~isempty(coltitle{n})
        h.title(n) = uicontrol(...
                'Parent',               hfig_inputdlg,...
                'String',               coltitle{n},...
                'Position',             [20+120*(n-1), figsize.y-60, 100, 15],...
                'Style',                'text',...
                'HorizontalAlignment',  'left',...
                'FontSize',             8,...
                'BackgroundColor',      figColor);
    end

    for m = 1:size(prompt{n}, 1)

            switch(prompt{n}{m, 2})
                case {'empty'}

                case {'numeric','string'}
                    
                    if strcmp(prompt{n}{m, 2}, 'numeric')
                        str_edit = num2str(defAns{n}{m});
                        if size(str_edit, 1) > 1
                            str_cell = cellstr(str_edit);
                            str_tmp = sprintf('%s;',str_cell{:});
                            str_edit = str_tmp(1:end-1);
                        end
                    else
                        str_edit = defAns{n}{m};
                    end
                    
                    posText{n}{m} = strcat('posText','(',num2str(m),',',num2str(n),')');
                    % 要把n，m结合放到一起查找
                    h.label{n}{m} = uicontrol(...
                        'Parent',               hfig_inputdlg,...
                        'String',               prompt{n}{m, 1},...
                        'Position',             [20+120*(n-1)+comp*(figsize.x/2 - 70), figsize.y-45-45*m, 100, 15],... %剪20
                        'Style',                'text',...
                        'HorizontalAlignment',  'left',...
                        'FontSize',             8,...
                        'BackgroundColor',      figColor);

                    h.text{n}{m} = uicontrol(...
                        'Parent',               hfig_inputdlg,...
                        'String',               str_edit,...
                        'Position',             [20+120*(n-1)+comp*(figsize.x/2 - 70), figsize.y-60-45*m, 100, 15],...
                        'Tag',                  posText{n}{m},...
                        'Style',                'edit',...
                        'HorizontalAlignment',  'left',...
                        'BackgroundColor',      [1 1 1]);
                
                case {'popup'}
                    posText{n}{m} = strcat('posText','(',num2str(m),',',num2str(n),')');
                    [pop_str, pop_pos] = specific_pops(dlg_title, defAns{n}{m});
                    % 要把n，m结合放到一起查找
                    h.label{n}{m} = uicontrol(...
                        'Parent',               hfig_inputdlg,...
                        'String',               prompt{n}{m,1},...
                        'Position',             [20+120*(n-1)+comp*(figsize.x/2 - 70), figsize.y-45-45*m, 100, 15],... %剪20
                        'Style',                'text',...
                        'HorizontalAlignment',  'left',...
                        'FontSize',             8,...
                        'BackgroundColor',      figColor);
                    
                    h.text{n}{m} = uicontrol(...
                        'Parent',               hfig_inputdlg,...
                        'String',               pop_str,...
                        'Value',                pop_pos,...
                        'Position',             [20+120*(n-1)+comp*(figsize.x/2 - 70), figsize.y-60-45*m, 100, 15],...
                        'Tag',                  posText{n}{m},...
                        'Style',                'popupmenu',...
                        'HorizontalAlignment',  'left',...
                        'BackgroundColor',      [1 1 1]);

                case {'file','file_txt','file_img'}
                    posText{n}{m} = strcat('posText','(',num2str(m),',',num2str(n),')');
                    h.label{n}{m} = uicontrol(...
                        'Parent',               hfig_inputdlg,...
                        'String',               prompt{n}{m,1},...
                        'Position',             [20+120*(n-1), figsize.y-45-45*m, 100, 15],... %剪20
                        'Style',                'text',...
                        'HorizontalAlignment',  'left',...
                        'FontSize',             8,...
                        'BackgroundColor',      figColor);
                
                    h.text{n}{m} = uicontrol(...
                        'Parent',               hfig_inputdlg,...
                        'String',               defAns{n}{m},...
                        'Position',             [20+120*(n-1), figsize.y-60-45*m, 84, 15],...
                        'Tag',                  posText{n}{m},...
                        'Style',                'edit',...
                        'HorizontalAlignment',  'left',...
                        'BackgroundColor',      [1 1 1]);

                    h.filebtn{n}{m} = uicontrol(...
                        'Parent',               hfig_inputdlg,...
                        'String',               '...',...
                        'UserData',             {prompt{n}{m,2},posText{n}{m}},...
                        'Position',             [20+120*(n-1)+85, figsize.y-60-45*m, 15, 15],...
                        'Style',                'pushbutton',...
                        'BackgroundColor',      btn_bkgColor,...
                        'Callback',             @doCallback);

                case {'file_img_*', 'box_file_img_*'}
                    posText{n}{m} = strcat('posText','(',num2str(m),',',num2str(n),')');
                    h.label{n}{m} = uicontrol(...
                        'Parent',               hfig_inputdlg,...
                        'String',               [prompt{n}{m,1},32,'*'],...
                        'Position',             [20+120*(n-1), figsize.y-45-45*m, 100, 15],... %剪20
                        'Style',                'text',...
                        'HorizontalAlignment',  'left',...
                        'FontSize',             8,...
                        'BackgroundColor',      figColor);
                
                    h.text{n}{m} = uicontrol(...
                        'Parent',               hfig_inputdlg,...
                        'String',               defAns{n}{m},...
                        'Position',             [20+120*(n-1), figsize.y-60-45*m, 84, 15],...
                        'Tag',                  posText{n}{m},...
                        'Style',                'edit',...
                        'HorizontalAlignment',  'left',...
                        'BackgroundColor',      [1 1 1]);

                    h.filebtn{n}{m} = uicontrol(...
                        'Parent',               hfig_inputdlg,...
                        'String',               '...',...
                        'UserData',             {prompt{n}{m,2},posText{n}{m}},...
                        'Position',             [20+120*(n-1)+85, figsize.y-60-45*m, 15, 15],...
                        'Style',                'pushbutton',...
                        'BackgroundColor',      btn_bkgColor,...
                        'Callback',             @doCallback);
                    
                case {'box_file_txt','box_file_img'}
                    posBF{n}{m} = strcat('posBF','(',num2str(m),',',num2str(n),')');
                    posText{n}{m} = strcat('posText','(',num2str(m),',',num2str(n),')');
                    figColor = 0.9*[1 1 1];

                    h.chbfile{n}{m} = uicontrol(...
                        'Parent',           hfig_inputdlg,...
                        'String',           prompt{n}{m,1},...
                        'Position',         [20+120*(n-1), figsize.y-42-45*m, 100, 18],...
                        'Tag',              posBF{n}{m},...
                        'Style',            'checkbox',...
                        'Value',            ~isempty(defAns{n}{m}),...
                        'BackgroundColor',  figColor);
                    brant_resize_ui(h.chbfile{n}{m});

                    h.text{n}{m} = uicontrol(...
                        'Parent',               hfig_inputdlg,...
                        'String',               defAns{n}{m},...
                        'Position',             [20+120*(n-1), figsize.y-60-45*m, 84, 15],...
                        'Tag',                  posText{n}{m},...
                        'Style',                'edit',...
                        'HorizontalAlignment',  'left',...
                        'BackgroundColor',      [1 1 1]);

                    h.filebtn{n}{m} = uicontrol(...
                        'Parent',               hfig_inputdlg,...
                        'String',               '...',...
                        'UserData',             {prompt{n}{m,2}(5:end),posText{n}{m}},...
                        'Position',             [20+120*(n-1)+85, figsize.y-60-45*m, 15, 15],...
                        'Style',                'pushbutton',...
                        'BackgroundColor',      btn_bkgColor,...
                        'Callback',             @doCallback);
                    
                case {'box_file_img_tmp'}
                    posBF{n}{m} = strcat('posBF','(',num2str(m),',',num2str(n),')');
                    posText{n}{m} = strcat('posText','(',num2str(m),',',num2str(n),')');
                    figColor = 0.9 * [1 1 1];

                    h.chbfile{n}{m} = uicontrol(...
                        'Parent',           hfig_inputdlg,...
                        'String',           prompt{n}{m,1},...
                        'Position',         [20+120*(n-1), figsize.y-42-45*m, 100, 18],...
                        'Tag',              posBF{n}{m},...
                        'Style',            'checkbox',...
                        'Value',            ~isempty(defAns{n}{m}),...
                        'BackgroundColor',  figColor);
                    brant_resize_ui(h.chbfile{n}{m});

                    h.text{n}{m} = uicontrol(...
                        'Parent',               hfig_inputdlg,...
                        'String',               defAns{n}{m},...
                        'Position',             [20+120*(n-1), figsize.y-60-45*m, 84, 15],...
                        'Tag',                  posText{n}{m},...
                        'Style',                'edit',...
                        'HorizontalAlignment',  'left',...
                        'BackgroundColor',      [1 1 1]);

                    h.filebtn{n}{m} = uicontrol(...
                        'Parent',               hfig_inputdlg,...
                        'String',               '...',...
                        'UserData',             {prompt{n}{m,2}(5:end),posText{n}{m}},...
                        'Position',             [20+120*(n-1)+85, figsize.y-60-45*m, 15, 15],...
                        'Style',                'pushbutton',...
                        'BackgroundColor',      btn_bkgColor,...
                        'Callback',             @doCallback);

                case 'box'
                    posChB{n}{m} = strcat('posChB','(',num2str(m),',',num2str(n),')');
                    figColor = 0.9*[1 1 1];

                    h.chb{n}{m} = uicontrol(...
                        'Parent',           hfig_inputdlg,...
                        'String',           prompt{n}{m,1},...
                        'Position',         [20+120*(n-1), figsize.y-60-45*m, 100, 19],...
                        'Tag',              posChB{n}{m},...
                        'Style',            'checkbox',...
                        'Value',            defAns{n}{m},...
                        'BackgroundColor',  figColor);
                    brant_resize_ui(h.chb{n}{m});
                
                case 'box_must'
                    posChB{n}{m} = strcat('posChB','(',num2str(m),',',num2str(n),')');
                    figColor = 0.9*[1 1 1];

                    h.chb{n}{m} = uicontrol(...
                        'Parent',           hfig_inputdlg,...
                        'String',           prompt{n}{m,1},...
                        'Enable',           'inactive',...
                        'Position',         [20+120*(n-1), figsize.y-60-45*m, 100, 18],...
                        'Tag',              posChB{n}{m},...
                        'Style',            'checkbox',...
                        'Value',            1,...
                        'BackgroundColor',  figColor);
                    brant_resize_ui(h.chb{n}{m});
                    
                case {'radio'}
                
                    posRB{n}{m} = strcat('posRB','(',num2str(m),',',num2str(n),')');
                    h.rb{n}{m} = uicontrol(...
                        'Parent',           hfig_inputdlg,...
                        'String',           prompt{n}{m,1},...
                        'Position',         [20+120*(n-1), figsize.y-60-45*m, 100, 19],...
                        'Tag',              posRB{n}{m},...
                        'Style',            'radiobutton',...
                        'Value',            defAns{n}{m},...
                        'BackgroundColor',  figColor,...
                        'Callback',         @singleSelection);
                    brant_resize_ui(h.rb{n}{m});
                    
                case 'rb_file'  % radiobutton
                    posRB{n}{m} = strcat('posRB','(',num2str(m),',',num2str(n),')');
                    posText{n}{m} = strcat('posText','(',num2str(m),',',num2str(n),')');

                    figColor = 0.9*[1 1 1];

                    h.rb{n}{m} = uicontrol(...
                        'Parent',           hfig_inputdlg,...
                        'String',           prompt{n}{m,1},...
                        'Position',         [20+120*(n-1), figsize.y-42-45*m, 100, 18],...
                        'Tag',              posRB{n}{m},...
                        'Style',            'radiobutton',...
                        'Value',            ~isempty(defAns{n}{m}),...
                        'BackgroundColor',  figColor,...
                        'Callback',         @singleSelection);
                    brant_resize_ui(h.rb{n}{m});

                    h.text{n}{m} = uicontrol(...
                        'Parent',               hfig_inputdlg,...
                        'String',               defAns{n}{m},...
                        'Position',             [20+120*(n-1), figsize.y-60-45*m, 84, 15],...
                        'Tag',                  posText{n}{m},...
                        'Style',                'edit',...
                        'HorizontalAlignment',  'left',...
                        'BackgroundColor',      [1 1 1]);

                    h.filebtn{n}{m} = uicontrol(... 
                        'Parent',               hfig_inputdlg,...
                        'String',               '...',...
                        'UserData',             {'file',posText{n}{m}},...
                        'Position',             [20+120*(n-1)+85, figsize.y-60-45*m, 15, 15],...
                        'Style',                'pushbutton',...
                        'BackgroundColor',      btn_bkgColor,...
                        'Callback',             @doCallback);
            end
    end
end

btnpos.x = figsize.x/2 - 30 + (1-dlg_rstbtn)*25;
btnpos.y = 60;

btnOpt = {...
    'OK',       [btnpos.x - 70 + (1-dlg_rstbtn)*10,	btnpos.y,  60, 20],     'ok_btn',       {@ok_cb, prompt, h, field_fun, subfield_fun, posChB, h_prep_main};...
    'Cancel',	[btnpos.x + 70 - (1-dlg_rstbtn)*60,	btnpos.y,  60, 20],     'cancel_btn',   @cancel_cb;...
    'Reset',    [btnpos.x,      btnpos.y,  60, 20],                         'rst_btn',      {@reset_cb, prompt, h, dlg_title}};

for n = 1:(2+dlg_rstbtn)
    h.btn(n) = uicontrol(...
        'Parent',           hfig_inputdlg,...
        'String',           btnOpt{n, 1},...
        'UserData',         btnOpt{n, 1},...
        'Position',         btnOpt{n, 2},...
        'Tag',              btnOpt{n, 3},...
        'Style',            'pushbutton',...
        'BackgroundColor',  btn_bkgColor,...
        'Callback',         btnOpt{n, 4});
end

function ok_cb(obj, evd, prompt, h, field_fun, subfield_fun, posChB, h_prep_main) %#ok<*INUSL>

ncols = length(prompt);
dlg_out = cell(ncols, 1);

for n = 1:ncols
    dlg_out{n} = cell(size(prompt{n},1),1);
    for m = 1:size(prompt{n},1)
        switch(prompt{n}{m,2})
            case {'file_img_*', 'box_file_img_*'}
                dlg_out{n}{m} = get(h.text{n}{m},'String');
            case {'file','file_txt','file_img', 'file_img_tmp'}
                dlg_out{n}{m} = get(h.text{n}{m},'String');
            case 'string'
                dlg_out{n}{m} = get(h.text{n}{m},'String');
            case {'numeric'}
                dlg_out{n}{m} = get(h.text{n}{m},'String');
            case 'popup'
                itemnum = get(h.text{n}{m},'Value');
                totstr = get(h.text{n}{m},'String');
                dlg_out{n}{m} = totstr{itemnum};
            case {'box', 'box_must'}
                dlg_out{n}{m} = get(findobj(gcf, 'Tag', posChB{n}{m}), 'Value');
            case {'box_file_txt', 'box_file_img', 'box_file_img_tmp'}
                if get(h.chbfile{n}{m},'Value')
                    dlg_out{n}{m} = get(h.text{n}{m},'String');
                end
            case 'rb_file'
                if get(h.rb{n}{m},'Value')
                    dlg_out{n}{m} = get(h.text{n}{m},'Value');
                end
        end
    end   
end

[sts, errmsgs] = brant_check_input(prompt, dlg_out);

if ~isempty(errmsgs)
    error(errmsgs);
elseif sts == 1
    data_fig = get(h_prep_main, 'Userdata');
    
    if isempty(subfield_fun)
        for n = 1:size(prompt{1}, 1)
            if ~isempty(prompt{1}{n, 3})
                data_fig.(field_fun{1}).(prompt{1}{n, 3}) = dlg_out{1}{n};
            end
        end
        if strcmpi(field_fun{1}, 'filter')
            for n = 1:size(prompt{1}, 1)
                if ~isempty(prompt{1}{n, 3})
                    data_fig.(field_fun{1}).(prompt{2}{n, 3}) = dlg_out{2}{n};
                end
            end
        end
    else
        for m = 1:numel(subfield_fun)
            for n = 1:size(prompt{m}, 1)
                if ~isempty(prompt{m}{n, 3})
                    data_fig.(field_fun{1}).(subfield_fun{m}).(prompt{m}{n, 3}) = dlg_out{m}{n};
                end
            end
        end
    end
    
    if data_fig.pref.sync == 1
        data_fig = brant_prep_sync(data_fig, field_fun{1});
    end
    
    h_curr_chb = findobj(h_prep_main, 'Tag', [field_fun{1}, '_chb']);
    set(h_curr_chb, 'Value', 1);
    data_fig.ind.(field_fun{1}) = 1;
    
    data_fig_new = brant_prep_run(data_fig, field_fun);
    
    data_fig.(field_fun{1}) = data_fig_new.(field_fun{1});
    set(h_prep_main, 'Userdata', data_fig);
    delete(gcf);
    brant_update_pre_disp;
end


function reset_cb(obj, evd, prompt, h, dlg_title)

vals = brant_reset(dlg_title);
for n = 1:ncols
    for m = 1:size(prompt{n},1)
        switch(prompt{n}{m,2})
        case {'numeric','string','file'}
            set(h.text{n}{m},'String',vals{n}{m});
        case 'popup'
            set(h.text{n}{m},'Value',1);
        case 'box'
            set(h.chb{n}{m},'Value',vals{n}{m});
        case {'box_file_txt','box_file_img'}
            if isempty(vals{n}{m})
                set(h.chbfile{n}{m},'Value',0);
            else
                set(h.chbfile{n}{m},'Value',1);
            end
            set(h.text{n}{m},'String',vals{n}{m});
        end
    end
end

function cancel_cb(obj, evd) %#ok<*INUSD>
delete(gcf);
        
function doCallback(obj, evd)
btnstyle = get(obj,'Style');
userdata = get(obj,'UserData');
if iscell(userdata)
    btntype = userdata;
else
    btntype = {userdata(1,:)};
end
switch(btnstyle)
    case 'radiobutton',
        switch(btntype{1})
            case ''
        end
    case 'pushbutton',
        switch(btntype{1})
            case 'OK'
                set(gcbf,'UserData','OK');
                uiresume(gcbf);
            case 'Cancel'
                set(gcbf,'UserData','Cancel');
                uiresume(gcbf);
            case 'Reset'
                set(gcbf,'UserData','Reset');
                uiresume(gcbf);
            case 'file'
                [file_input,pathname] = uigetfile('*.*');
                if ischar(file_input)
                    filepath = fullfile(pathname, file_input);
                    set(findobj(0,'Tag',btntype{2}),'String',filepath);
                end
            case 'file_txt'
                [file_input,pathname] = uigetfile('*.txt');
                if ischar(file_input)
                    filepath = fullfile(pathname, file_input);
                    set(findobj(0,'Tag',btntype{2}),'String',filepath);
                end
            case {'file_img','file_img_*'}
                [file_input,pathname] = uigetfile({'*.nii;*.img','image files(*.nii, *.img)'});
                if ischar(file_input)
                    filepath = fullfile(pathname, file_input);
                    set(findobj(0,'Tag',btntype{2}),'String',filepath);
                end
            case {'file_img_tmp', 'box_file_img_*'}
                brant_tmp = fullfile(fileparts(which('brant')), 'template');
                [file_input, pathname] = uigetfile({'*.nii;*.img', 'image files(*.nii, *.img)'}, 'Select a file', ['', brant_tmp, '']);
%                 [file_input, pathname] = uigetfile({[brant_tmp, filesep, '*.nii;*.img'],'image files(*.nii, *.img)'});
                if ischar(file_input)
                    filepath = fullfile(pathname, file_input);
                    set(findobj(0,'Tag',btntype{2}),'String',filepath);
                end
        end
end

function singleSelection(obj, evd)
obj_parent = get(obj, 'Parent');
radiobox = findobj(obj_parent, 'Style', 'radiobutton');

arrayfun(@(x) set(x, 'Value', 0), radiobox);
set(obj, 'Value', 1);

% posRB = get(obj,'Position');
% for n = 1:length(radiobox)
%     if radiobox(n) ~= obj
%         postmp = get(radiobox(n),'Position');
%         if postmp(1) == posRB(1)
%             set(radiobox(n),'Value',0);
%         end
%     end
% end
% set(obj,'Value',1);

function [pop_str, pop_pos] = specific_pops(dlg_title, val)
switch(dlg_title)
    case 'normalize'
        pop_str = {'mni','imni','rigid','subj','eastern','none'};
        pop_pos = find(cell2mat(cellfun(@(x) strcmp(x, val), pop_str, 'UniformOutput', false)));
end
