function jobout = brant_net_measure_defaults
prompt = {  'assortative mixing',...      
            'neighbor degree',...
            'betweenness centrality',...
            ...'betweenness rw',...
            ...'betweenness spe',...
            ...'betweenness spv',...
            'clustering coefficient',...
            'degree',...
            'fault tolerance',...
            'global efficiency',...
            'local efficiency',...
            'resilience',...
            'shortest path length',...
            'transitivity',...
            'vulnerability',...
            'small worldness'};
        
for m = 1:numel(prompt)
    jobout.(strrep(prompt{m}, ' ', '_')) = 0;
end

jobout.sw.keep_connectivity = 0;
jobout.sw.num_simulation = 100;
