function prompt = brant_postprocess_funcions(functype)

switch(functype)
    case 'FC'
        prompt = {  'Draw ROI';...
                    'Merge/Extract ROIs'
                    'ROI Calculation';...
                    };
    case 'SPON'
        prompt = {  'AM';...
                    'ALFF/fALFF';...
                    'fGn';...
                    'ReHo';...
                    'FCD';...
                    };
    case 'STAT'
        prompt = {  'Statistics';...
                    'IBMA';...
                    };
    case 'UTILITIES'
        prompt = {  'DICOM Convert';...
                    'Delete Timepoints';...
                    'Head Motion Est';...
                    'Visual Check';...
                    'TSNR';...
                    'ROI Coordinates';...
                    'Extract Mean';...
                    ...Pre-process New';...
                    };
    case 'NET'
        prompt = {  'Network Calculation';...
                    'Network Statistics';...
                    };
    case 'VIEW'
        prompt = {  'Surface Mapping';...
                    'ROI Mapping';...
                    'Network Visualization'};
    case 'PREPROCESS'
        prompt = {  'Slice Timing';...
                    'Realign';...
                    'Coregister';...
                    'Normalise';...
                    'Denoise';...
                    'Smooth'};
    otherwise
        warndlg('Unknown inputs!');
end
