function [prompt, defAns] = brant_postprocess_parameters(userdata)

mask_nii = fullfile(fileparts(which('brant')), 'template', 'fmaskEPI_V2mm.nii');
aal_nii = fullfile(fileparts(which('brant')), 'template', 'aal_2mm.nii');
if exist(mask_nii, 'file') ~= 2 || exist(mask_nii, 'file') ~= 2
    mask_nii = '';
    aal_nii = '';
    warning('template or mask not found in %s\n', fullfile(fileparts(which('brant')), 'template'));
end

switch(userdata)
    case 'Dicom Convert'
        prompt = {  'chb:num_bin'           ,		'parallel'      ,       0       ,       'parallel computing (cpu)'      ;...
                    'edit:num_short'        ,		'workers'       ,       0       ,       'workers'       ;...
                    'seperator:str'         ,       ''              ,       ''      ,       'set ''workers'' to negative to use all workers'     ;...
                    'chb:num_bin'           ,		'is4d'          ,       1       ,       'convert to 4d' ;...
                    'edit:num_short_infos'	,		'chk_tps'       ,       0       ,       'timepoints:(optional)'    ;...
                    'edit:num_short_infos'	,		'del_tc'        ,       10      ,       'delete first:timepoints'  ;...
                    'edit:str_short'        ,		'prefix'        ,       'brant'  ,       'prefix'        ;...
                    'edit:num_short'        ,		'nm_pos'        ,       1       ,       'name pos'      ;...
                    'edit:disp_dirs'        ,		'subj_list'     ,       ''      ,       'src paths'     ;...
                    'edit:str_dir'          ,		'out_dir'       ,       ''      ,       'output path'   };
        
    case {'Head Motion Estimate'}
        prompt = {  'radio:vertical'    ,       'data_same_calc_rp:data_diff_rp'   ,   	[0,1]		,       'blank:Data in one directory:Data in different directories'     ;...
                    'edit:str_dir'		,		'out_dir'                       ,		''          ,       'output path'   };
        
    case 'Visual Check'
        prompt = {  'edit:num_short'    ,		'num_chk'               ,           2		,       'num chk'                ;...
                    'radio:vertical'    ,       'data_same:data_diff'   ,   	[1,0]		,       'blank:Data in one directory:Data in different directories'};
    case 'TSNR'
        prompt = {  'edit:str_img'              ,		'mask_fn'               ,       mask_nii	,       'mask'                          ;...
                    'edit:str_short'            ,		'filetype'              ,		'*.nii'     ,       'filetype'                      ;...
                    'edit:num_short'            ,		'nm_pos'                ,		1           ,       'name pos'                      ;...
                    'edit:disp_dirs'            ,		'subj_list'             ,		''          ,       'subj paths'                    ;...
                    'edit:str_dir'              ,		'out_dir'               ,       ''          ,       'output path'   };
    case{'Draw ROI'}
        prompt = {  'radio:horizontal_txt'      ,		'mni:tal'	,       [1,0]       ,       'space:MNI:TAL'         ;...
                    'radio:horizontal_txt'      ,		'sphere:box',       [1,0]		,       'type:sphere:box'       ;...
                    'radio:horizontal_txt'      ,		'mm:vox'	,       [1,0]		,       'unit:mm:vox'           ;...
                    'chb:num_bin'               ,		'mask_roi'	,           1		,       'mask roi afterwards'   ;...
                    'edit:num_short'            ,		'radius'	,           4		,       'radius'                ;...
                    'edit:num_vec'              ,		'coords'	,      '0,0,0;'		,       'coords'                ;...
                    'edit:str_img'      		,		'mask_fn'	,       mask_nii	,       'mask'                  ;...
                    'edit:str_dir'              ,		'out_dir'	,           ''		,       'output path'           };
        
    case{'ROI - Whole Brain', 'ROI - ROI'}
        prompt = {  'edit:num_short'	,		'timepoints'	,		0           ,       'timepoints'                    ;...
                    'edit:str_img'      ,		'mask_fn'       ,       mask_nii    ,       'mask'                          ;...
                    'edit:str_dir'      ,		'out_dir'       ,       ''          ,       'output path'                   ;...
                    'chb:num_bin'		,		'r2z'           ,		1           ,       'r value to z value transform'  ;...
                    'radio:vertical'    ,       'roi_multiple:roi_single'   ,   	[0,1]		,       'blank:multiple roi mask files:template img tagged by numbers'     ;...
                    'radio:vertical'    ,       'data_same:data_diff'       ,   	[0,1]		,       'blank:Data in one directory:Data in different directories'     };
        
    case{'Whole Brain'}
        prompt = {  'edit:num_short'	,		'timepoints'	,		0           ,       'timepoints'                    ;...
                    'edit:str_short'	,		'filetype'      ,		'sfd*.nii'	,       'filetype'                      ;...
                    'edit:str_img'      ,		'mask_fn'       ,       mask_nii    ,       'mask'                          ;...
                    'edit:str_dir'      ,		'out_dir'       ,       ''          ,       'output path'                   ;...
                    'chb:num_bin'		,		'r2z'           ,		0           ,       'r value to z value transform'  ;...
                    'edit:num_short'	,		'nm_pos'        ,		1           ,       'name pos'                      ;...
                    'edit:disp_dirs'	,		'subj_list'     ,		''          ,       'subj paths'                    };
                
    case 'Short Distant Connections',
        prompt = {  'chb:num_bin'		,		'gpu'           ,		0           ,       'OpenCL supported GPU'          ;...
                    'chb:num_bin'		,		'cpu'           ,		0           ,       'OpenCL supported CPU'          ;...
                    'edit:str_short'	,		'gpub'          ,		256         ,       'gpub'                          ;...
                    'edit:str_short'	,		'cpub'          ,		14          ,       'cpub'                          ;...
                    'edit:str_short'	,		'thres_corr'    ,		'0.5'       ,       'corr thres'                    ;...
                    'edit:str_short'	,		'thres_dist'    ,		'14:2:18'   ,       'dist thres'                    ;...
                    'edit:str_img'      ,		'mask_fn'       ,       mask_nii    ,       'mask'                          ;...
                    'edit:str_short'	,		'filetype'      ,		'^sfd.*nii$',       'filetype reg'                  ;...
                    'edit:num_short'	,		'nm_pos'        ,		1           ,       'name pos'                      ;...
                    'edit:str_dir'      ,		'src_dir'       ,       ''          ,       'source dir'                    ;...
                    'chb:num_bin'		,		'normalize'     ,		1           ,       'normalize to mean value'       ;...
                    'edit:str_dir'      ,		'out_dir'       ,       ''          ,       'output path'                   };
        
    case{'AM', 'fGn'}
        prompt = {  'edit:num_short'	,		'timepoints'	,		0           ,       'timepoints'                    ;...
                    'chb:num_bin'		,		'nor'           ,		0           ,       'normalize transform'           ;...
                    'edit:str_img'      ,		'mask_fn'       ,       mask_nii    ,       'mask'                          ;...
                    'edit:str_dir'      ,		'out_dir'       ,       ''          ,       'output path'                   ;...
                    'radio:vertical'    ,       'data_same:data_diff'   ,   	[0,1]		,       'blank:Data in one directory:Data in different directories'     };
        
    case{'ALFF'}
        prompt = {  'edit:num_short'	,		'timepoints'	,		''          ,       'timepoints'                                                ;...
                    'edit:num_short'	,		'tr'            ,		''          ,       'tr'                                                        ;...
                    'seperator:str'     ,       ''              ,       ''          ,       '====================================================='     ;...
                    'seperator:str'     ,       ''              ,       ''          ,       'frequency cutoff: (e.g. 0.01~0.1 Hz)'                      ;...
                    'edit:num_short'	,		'lower_thr'     ,       ''          ,       'lower (Hz)'                                                ;...
                    'edit:num_short'	,		'higher_thr'    ,		''          ,       'higher (Hz)'                                               ;...
                    'seperator:str'     ,       ''              ,       ''          ,       '====================================================='     ;...
                    'chb:num_bin'		,		'nor'           ,		0           ,       'normalize transform'                                       ;...
                    'edit:str_img'      ,		'mask_fn'       ,       mask_nii    ,       'mask'                                                      ;...
                    'edit:str_dir'      ,		'out_dir'       ,       ''          ,       'output path'                                               ;...
                    'radio:vertical'    ,       'data_same:data_diff'   ,   	[0,1]		,       'blank:Data in one directory:Data in different directories'     };

    case{'ReHo'}
        prompt = {  'edit:num_short'	,		'timepoints'	,		0                   ,       'timepoints'                    ;...
                    'pop:num3_6_18_27'  ,		'neighbout_num'	,       {'6';'18';'26'}     ,       'neighbour number'              ;...
                    'chb:num_bin'		,		'nor'           ,		0                   ,       'normalize transform'           ;...
                    'edit:str_img'      ,		'mask_fn'       ,       mask_nii            ,       'mask'                          ;...
                    'edit:str_dir'      ,		'out_dir'       ,       ''                  ,       'output path'                   ;...
                    'radio:vertical'    ,       'data_same:data_diff'   ,   	[0,1]		,       'blank:Data in one directory:Data in different directories'     };

    case{'Net Construct'}
        prompt = {  'edit:num_short'	,		'node_num'	,		100           ,       'node num'                    ;...
                    'edit:num_vec'      ,		'same_thres'	,		'0.2:0.01:0.3'                   ,       'threshold of network'                    ;...
                    'edit:num_vec'      ,		'same_sparsity'	,		'0.05:0.01:0.2'                   ,       'sparsity for network'                    ;...
                    'chb:num_bin'		,		'mst'                       ,		1           ,       'minimun spanning tree'  ;...
                    'radio:vertical'    ,       'mat_same:mat_diff'       ,   	[0,1]		,       'blank:Data in one directory:Data in different directories'     ;...
                    'radio:vertical'    ,       'ts_mat:corr_mat'           ,   	[0,1]		,       'blank:time series:correlation matrix';...
                    'chb:num_bin'		,		'r2z'                       ,		1           ,       'r value to z value transform'  ;...
                    'edit:str_dir'      ,		'out_dir'                   ,       ''          ,       'output path'                                               ;...
                    };
        
    case{'Net Measure'}
        prompt = {  'edit:num_short'	,		'node_num'	,		100           ,       'node number'                    ;...
                    'radio:vertical'    ,       'binary:weighted'           ,   	[1,0]		,       'blank:Bianry:Weighted';...
                    'edit:disp_net_measure'           ,		'net_measure_methods'                  ,		''          ,       'Network Measurements'              ;...
                    'radio:vertical'    ,       'mat_same:mat_diff'       ,   	[1,0]		,       'blank:Data in one directory:Data in different directories'     ;...
                    'edit:str_dir'      ,		'out_dir'                   ,       ''          ,       'output path'                                               ;...
                    };
    case{'Net Statistics'}
        prompt = {  'edit:num_short'	,		'node_num'	,		100           ,       'node num'                    ;...
                    'edit:num_vec'	,		'same_thres'	,		'0.2:0.01:0.3'                   ,       'threshold of network'                    ;...
                    'edit:num_vec'	,		'same_sparsity'	,		'0.05:0.01:0.2'                   ,       'sparsity for network'
                    'edit:num_vec'	,		'group_1_ID'	,		'1:15'                   ,       'ID for group 1'                    ;...
                    'edit:num_vec'	,		'group_2_ID'	,		'16:30'                  ,       'ID for gourp 2'  ;...
                    'edit:disp_infos'           ,		'covs'                  ,		''          ,       'covariates'                  ;...                                           ;...
                    'radio:vertical'    ,       'mat_same:mat_diff'       ,   	[1,0]		,       'blank:Data in one directory:Data in different directories'     ;...
                    'chb:num_bin'		,		'randperm_test'                       ,		1           ,       'permutation test'  ;...
                    'edit:str_dir'      ,		'out_dir'                   ,       ''          ,       'output path'                                               ;...
                    };
        
        
    case{'Voxel Based', 'Mat Based'}
        prompt = {  'seperator:str'             ,       ''                      ,       ''          ,       'Statistical Analysis'                                          ;...
                    ...'radio:horizontal_txt'      ,       'matlab:spm'            ,   	[1,0]		,       'ttest2:matlab:spm'                                             ;...
                    'edit:str_img'              ,		'mask_fn'               ,       mask_nii    ,       'mask'                                                          ;...
                    'radio:vertical'            ,       'data_same:data_diff'   ,   	[1,0]		,       'blank:Data in one directory:Data in different directories'     ;...
                    'edit:disp_infos'           ,		'covs'                  ,		''          ,       'covariates'                                                    ;...
                    'edit:str_dir'              ,		'out_dir'               ,       ''          ,       'output path'                                                   };
        
    case{'IBMA'}
        prompt = {  'seperator:str'             ,       ''                      ,       ''          ,       'Image Based Meta Analysis'                                     ;...
                    'edit:str_img'              ,		'mask_fn'               ,       mask_nii    ,       'mask'                                                          ;...
                    'chb:num_bin'               ,		'stouffer'              ,		0           ,       'Stouffer''s z-score'                   ;...
                    'chb:num_bin'               ,		'fisher'                ,		0           ,       'Fisher''s method'                      ;...
                    'chb:num_bin'               ,		'fem'                   ,		0           ,       'Fixed Effect Model'                    ;...
                    'chb:num_bin'               ,		'mem'                   ,		0           ,       'Mixed Effect Model'                    ;...
                    'chb:num_bin'               ,		'friston'               ,		0           ,       'Friston''s method'                     ;...
                    'chb:num_bin'               ,		'nicolas'               ,		0           ,       'Nicolas''s method (Overlap)'           ;...
                    'chb:num_bin'               ,		'inv_t'                 ,		0           ,       'Inverse t map'                         ;...
                    'radio:vertical'            ,       'data_same:data_diff'   ,   	[1,0]		,       'blank:Data in one directory:Data in different directories'     ;...
                    'seperator:str'             ,       ''                      ,       ''          ,       'Sample size for each group & site'                                     ;...
                    'edit:disp_infos'           ,		'covs'                  ,		''          ,       'sample size'                                                    ;...
                    'edit:str_dir'              ,		'out_dir'               ,       ''          ,       'output path'                                                   };
                
    case 'Visual'
        prompt = {  'edit:str_txt'              ,		'surface'                   ,       ''          ,       'surface'                           ;...
                    'edit:num_short'            ,		'alpha'                     ,       0.2         ,       'alpha'                             ;...
                    'radio:horizontal_txt'      ,		'brain_halves:whole_brain'	,       [1,0]       ,       'display mode:halves:whole'         ;...
                    'edit:view'                 ,     'select_view'               ,       '-select view-',    'az:el'                                  ;...
                    %'chb:num_bin'               ,		'med_lat'                   ,		0           ,       'medial and lateral'                ;...
                    'seperator:str'             ,       ''              ,       ''          ,       '====================================================='     ;...
                    'edit:str_txt'              ,		'node'                      ,       ''          ,       'node'                              ;...
                    'chb:num_short'             ,     'node_size_eq:node_size'              ,       [0 3]          ,       'node size equal'                   ;...
                    %'edit:num_short'            ,     'node_size'              ,       3           ,        ''                                 ;...
                    'radio:vertical_color'      ,		'node_same_color:node_module'         ,       [1,0]       ,       'color:same color for all nodes:node color for module'           ;...
                    'seperator:str'             ,       ''              ,       ''          ,       '====================================================='     ;...
                    'edit:str_txt'              ,		'edge'                      ,       ''          ,       'edge'                              ;...
                    'edit:num_short'            ,		'thickness'                     ,       2         ,       'thickness'                             ;...
                    'chb:num_bin'               ,		'adj_edge_color'              ,       0           ,       'adjust edge color'                   ;...
                    'edit:text_color'           ,		'pos_color:neg_color'                      ,       ''          ,       'positive::negtive'       ;...
                    'edit:str_long_btn'         ,		'threshold_str'                      ,       'edge < 0.5 && edge > 0.1'          ,       'threshold'     };
    case 'Reslice'
        prompt = {  'seperator:str'             ,       ''              ,       ''          ,       'output parameters'     ;...
                    'edit:num_short'            ,		'tar_vox_size'                  ,		'3 3 3'     ,       'voxelsize'                        ;...
                    'radio:vertical'            ,		'select_files:select_folders'   ,       [1,0]       ,       'blank:select files:select folders'     ;...
                    'edit:str_dir'              ,		'out_dir'                       ,       ''          ,       'output path'                           ;...
                    };

    case 'select_spm'
        prompt = {'edit:disp_files'             ,		'spm_folder'             ,		''          ,       'data dir'};
        
    case 'select_txt'
        prompt = {'edit:disp_files'             ,		'txt_folder'             ,		''          ,       'data dir'};
        
    case 'data_same'
        prompt = {  'edit:str_short'            ,		'filetype'              ,		'*.nii'     ,       'filetype'                                                      ;...
                    'edit:num_short'            ,		'nm_pos'                ,		1           ,       'name pos'                      ;...
                    'chb:num_bin'               ,		'rec'                   ,       0           ,       'search recursively'                   ;...
                    'edit:disp_files'           ,		'subj_list'             ,		''          ,       'data dir'                                                    };
        
    case 'data_diff'
        prompt = {  'edit:str_short'            ,		'filetype'              ,		'*.nii'     ,       'filetype'                      ;...
                    'edit:num_short'            ,		'nm_pos'                ,		1           ,       'name pos'                      ;...
                    'edit:disp_dirs'            ,		'subj_list'             ,		''          ,       'subj paths'                    };
        
    case 'mat_same'
        prompt = {  'edit:str_short'            ,		'filetype'              ,		'*.mat'     ,       'filetype'                                                      ;...
                    'edit:num_short'            ,		'nm_pos'                ,		1           ,       'name pos'                      ;...
                    'chb:num_bin'               ,		'rec'                   ,       0           ,       'search recursively'                   ;...
                    'edit:disp_files'           ,		'subj_list'             ,		''          ,       'data dir'                                                    };
        
    case 'mat_diff'
        prompt = {  'edit:str_short'            ,		'filetype'              ,		'*.mat'     ,       'filetype'                      ;...
                    'edit:num_short'            ,		'nm_pos'                ,		1           ,       'name pos'                      ;...
                    'edit:disp_dirs'            ,		'subj_list'             ,		''          ,       'subj paths'                    };
        
    case 'data_same_calc_rp'
        prompt = {  'edit:str_short'            ,		'filetype'              ,		'rp_*.txt'      ,       'filetype'                                                      ;...
                    'edit:num_short'            ,		'nm_pos'                ,		1           ,       'name pos'                      ;...
                    'chb:num_bin'               ,		'rec'                   ,       0           ,       'search recursively'                   ;...
                    'edit:disp_files'           ,		'subj_list'             ,		''              ,       'data dir'                                                    };
        
    case 'data_diff_rp'
        prompt = {  'edit:str_short'            ,		'filetype'              ,		'rp_*.txt'  ,       'filetype'                      ;...
                    'edit:num_short'            ,		'nm_pos'                ,		1           ,       'name pos'                      ;...
                    'edit:disp_dirs'            ,		'subj_list'             ,		''          ,       'subj paths'                    };
        
    case 'roi_multiple'
        prompt = {  'edit:str_short'	,		'roi_filetype'  ,		'roi*.nii'	,       'roi filetype'                  ;...
                    'edit:disp_files'   ,		'roi_list'      ,		''          ,       'roi dir'                       };
        
    case 'select_files'
        prompt = {  'edit:num_short'    ,		'nm_pos'        ,		1           ,       'name pos'                      ;...
                    'chb:num_bin'       ,		'in_text'       ,       0           ,       'files in text file'                 ;...
                    'edit:disp_files'   ,		'sel_files'     ,		''          ,       'select files'                     };
                
    case 'select_folders'
        prompt = {  'edit:num_short'    ,		'nm_pos'        ,		1           ,       'name pos'                      ;...
                    'edit:str_short'    ,		'filetype'      ,		'*.nii'     ,       'filetype'                      ;...
                    'chb:num_bin'       ,		'in_text'       ,       0           ,       'paths in text file'                 ;...
                    'edit:disp_files'   ,		'sel_dirs'      ,		''          ,       'select dirs'                     };
                
    case 'roi_single'
        prompt = {  'edit:str_img'              ,		'template_fn'               ,       aal_nii 	,       'template'                  };
        
    case 'ts_mat'
        prompt = {'edit:num_short'	,		'timepoints'	,		0                   ,       'timepoints'                    };
    case 'Binary'
        prompt = {'edit:num_short'	,		'Binary'	,		1                   ,       'Binary'                    };
    otherwise
        prompt = '';
        defAns = '';
end
