function strlen_table_ind = brant_ui_size

strlen_table_ind = {'parallel computing (cpu)',                 134		160		;...
                    'workers',                                  50		50		;...
                    'num chk',                                  50		50		;...
                    '(optional)',                               60		60		;...
                    'adjust edge color',                        102		133		;...
                    'convert to 4d',                            83		120		;...
                    'from text file',                           80		105		;...
                    'brain mask',                               60		60		;...
                    'show colorbar',                            90		120		;...
                    'group filter',                             75		60		;...
                    'extract mean',                             85		120		;...
                    'display colorbar',                         97		103		;...
                    'display surface',                          97		115		;...
                    'display axis',                             80		103		;...
                    'node size equal',                          96		103		;...
                    'edge size equal',                          96		103		;...
                    ...'r to z transform',                         97		100		;...
                    'roi tagged by numbers',                    127		143		;...
                    'thresholds of correlation coefficient',    193		220		;...
                    'thresholds of sparsity',                   132		170		;...
                    'user defined node color',                   137		200		;...
                    'field of correlation',                     115		137		;...
                    'discard subjects without info',            160		220		;...
                    'normalize transform',                      115		150		;...
                    'Partial correlation',                      105		137		;...
                    'Pearson''s correlation',                   122		200		;...
                    'discard outliers (3 std)',                 132		143		;...
                    'medial and lateral',                       102		133		;...
                    'show node labels',                         110		150		;...
                    'Permutation test',                         100		130		;...
                    'Student''s t-test of mean',                140		180		;...
                    'output p value',                           90		98		;...
                    'drop nan voxels',                          100		98		;...
                    'same size',                                95		98		;...
                    'same node color',                          100		150		;...
                    'view angle',                               80		60		;...
                    'spin&save',                                80      100     ;...
                    'FDR',                                      40		40		;...
                    'FDR2',                                     45		50		;...
                    'Bonf',                                     45		50		;...
                    'FWE',                                      43		40		;...
                    'Data in different directories',            150		180		;...
                    'output to one roi file',                   119		185		;...
                    'Input 4-D nifti files (3-D if not selected)',205		220		;...
                    '4D nifti files (3D if unchecked)',         166		220		;...
                    'Data in one directory',                    119		143		;...
                    'node color for module',                    124		143		;...
                    'module color',                             85      120      ;...
                    'roi to roi correlation',                   113		160		;...
                    'Bonferroni Correction',                    124		143		;...
                    'roi to whole brain correlation',           159		210		;...
                    'MNI',                                      40		42		;...
                    'TAL',                                      40		42		;...
                    'box',                                      40		55		;...
                    'sphere',                                   55		70		;...
                    'mm',                                       35		50		;...
                    'vox',                                      37		41		;...
                    'mask roi afterwards',                      117		180		;...
                    'delete timepoints only',                   119		119		;...
                    'same color for all nodes',                 135		133     ;...
                    'same color for all edges',                 135		133     ;...
                    'multiple roi mask files',                  120		120		;...
                    'normalize to mean value',                  135		135		;...
                    'extract mean - 3D',                        120     120     ;...
                    'time series',                              72,     58      ;...
                    'correlation matrix',                       102,    135     ;...
                    'node num',                                 120     120     ;...
                    'degree',                                   120     120     ;...
                    'global efficiency',                        120     120     ;...
                    'local efficiencey',                        120     120     ;...
                    'transivity',                               120     120     ;...
                    'cluster coefficienct',                     160     160     ;...
                    'shortest path length',                     160     160     ;...
                    'OpenCL supported GPU',                     160     160     ;...
                    'OpenCL supported CPU',                     160     160     ;...
                    'small worldness',                          140     140     ;...
                    'vulnerability',                            120     120     ;...
                    'fault tolerance',                          120     120     ;...
                    'permutation test',                         120     120     ;...
                    'input mats of p values',                   160     160     ;...
                    'Minimun Spanning Tree',                    130     160     ;...
                    'search recursively',                       120     120     ;...
                    'Stouffer''s z-score',                      117		135		;...
                    'Fisher''s method',                         120     120     ;...
                    'Fixed Effect Model',                       120     120     ;...
                    'Mixed Effect Model',                       120     120     ;...
                    'paths in text file',                       100     100     ;...
                    'files in text file',                       90     90     ;...
                    'select files',                             75     75     ;...
                    'select folders',                           85     85     ;...
                    'Friston''s method',                        120     120     ;...
                    'Nicolas''s method (Overlap)',              165     180     ;...
                    'multiple testing correction',              165     180     ;...
};
