function prompt = brant_postprocess_funcions(functype)

switch(functype)
    case 'FC'
        prompt = {  'Draw ROI';...
                    'Merge/Extract ROIs'
                    'ROI Calculation';...
                    'FCD';...
                    };
    case 'SPON'
        prompt = {  'AM';...
                    'ALFF/fALFF';...
                    'fGn';...
                    'ReHo'};
    case 'STAT'
        prompt = {  'Statistics';...
                    'IBMA';...
                    };
    case 'UTILITIES'
        prompt = {  'Dicom Convert';...
                    'Del Timepoints';...
                    'Head Motion Est';...
                    'Visual Check';...
                    'TSNR';...
                    ...'Reslice';...
                    'Mask To Table';...
                    'Extract Mean';...
                    ...'Extract Mean Adv'
                    };
                
    case 'NET'
        prompt = {  ...'Network Construct';...
                    ...'Network Calcs';...
                    'Network Calculation';...
                    'Network Statistics';...
                    };
                
    case 'VIEW'
        prompt = {  ...'Surface';...
                    'Surface Mapping';...
                    'ROI Mapping';...
                    'Network Visualization'};
    otherwise
        warndlg('Unknown inputs!');
end
